server:
  port: 8090

spring:
  application:
    name: msvc-student
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDb
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Configurar el Config Server
  config:
    import: optional:configserver:http://localhost:8888

# Configuración de Eureka (Para que el MCSV se registre en Eureka)
eureka:
  instance:
    hostname: localhost
  
  client:
    service-url:
      default-zone: http://localhost:8761/eureka