server:
  port: 9090

spring:
  application:
    name: msvc-course
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courseDb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Configuración de Eureka (Para que el MCSV se registre en Eureka)
eureka:
  instance:
    hostname: localhost
  
  client:
    service-url:
      default-zone: http://localhost:8761/eureka