# No registrar el mcsv en Eureka
eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # Gateway activo, el que va a redireccionar a los msvc
          enabled: true
      # Configurar las rutas de los msvc    
      routes:
        - id: students
          uri: http://localhost:8090
          # Accede a cualquier recurso del msvc-student
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          # Accede a cualquier recurso del msvc-course
          predicates:
            - Path=/api/course/**