server:
  port: 8080

spring:
  # Configurar el Config Server
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # Gateway activo, el que va a redireccionar a los msvc
          enabled: true
      # Configurar las rutas de los msvc    
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            # Accede a cualquier recurso del msvc-student
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            # Accede a cualquier recurso del msvc-course
            - Path=/api/course/**